development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: Where2_production
# redis://localhost:6379/1
# redis://where2-806.herokuapp.com/
